Resolving Issues
maayarosama/Web_Components pull request #5
Opened 2022-11-27 16:12 UTC by maayarosama

### Notes 
Create your own weblet section still needs some modifications.

### Related Issues

#1 
#2 
#3 
#4

2022-11-28 10:53 UTC, xmonader commented on tutorial.md
>  ### What are web components?
Can we please add an intro text of what is being explained in this tutorial what are the goals :) ?

2022-11-28 10:53 UTC, xmonader commented on tutorial.md
> +In a svelete projects it usually consists of one or more components. Each components is a reusable self-contained block with its HTML, CSS and JaveScript/Typescript encapsulated.
typo: svelete -> svelte

2022-11-28 11:02 UTC, xmonader commented on tutorial.md
>  One of the main reason svelte is used in developing our [weblets](https://play.grid.tf/#/) is components can be used as standalone packages that work anywhere.
is components -> is

2022-11-28 11:02 UTC, xmonader commented on tutorial.md
> +2. We need to create a new image in ubuntu based image that supports ssh server and run our pasty image in it.(inserts details here)
(inserts details here) is still missing

2022-11-28 11:03 UTC, xmonader commented on tutorial.md
> +Add a ```Network.ts``` file:
please explain the purpose of this file (e.g describe the functions provided)

2022-11-28 11:03 UTC, xmonader commented on tutorial.md
> +Add a ```rootFs.ts``` file:
please explain this file too

2022-11-28 14:29 UTC, rawdaGastan requested changes
simple comments :D

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
>  Web Components is a bunch of different technologies bundeled together allowing the user to create reusable custom elements with their functionalities, which later on can be re-used and utilized in yo
bundeled -> bundled

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +        Custom Elements specifications lay the foundation for designing and using new types of DOM elements. According to it authors can define HTML tags with their behaviours and styles.
behaviours -> behaviors

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +Svelte is a modern JavaScript framework used to build fast web applications. Users use Svelte to either build the entire app woth it or build reusable components that can work as standalone packages
woth -> with

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +    In ```store.js``` file:
store.js -> stores.js

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +        function decrement() {
why adding 2 scripts? I think decrement() is not used

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
>  One of the main reason svelte is used in developing our [weblets](https://play.grid.tf/#/) is components can be used as standalone packages that work anywhere.
reason -> reasons

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
>  - Create a a weblet
Create a a weblet -> Create a weblet

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
>  RUN mkdir ./file_name/
I think we need to explain this more? where to put it in the docker?

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +Or Navigate to your repository in the contributers section from the Zero-Os Hub and navigate to the newly created Flist.
contributers -> contributors

2022-11-28 14:29 UTC, rawdaGastan commented on tutorial.md
> +Now that the configuration is all set up, we need to prepare our classes and depoloyment files.
depoloyment -> deployment

2022-11-29 14:31 UTC, rawdaGastan commented
my comments are done 👍🏻

2022-11-29 15:52 UTC, xmonader commented
great job!!!

2022-11-29 15:53 UTC, merged